# fly.toml app configuration file generated for factoryflow-sensor on 2025-10-17T03:20:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'factoryflow-sensor'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
