apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: factoryflow
data:
  SERVER_PORT: "8080"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_GROUP_ID: "factoryflow-backend"
  KAFKA_TOPIC: "line1.sensor"
  KAFKA_AUTO_OFFSET: "latest"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "factoryflow"
  DB_USER: "factoryuser"
  DB_PASSWORD: "factorypass"
  DB_SSLMODE: "disable"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: factoryflow
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: factoryflow/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: factoryflow
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: factoryflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: backend-service
spec:
  rules:
  - host: api.factoryflow.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8080